Homework 4
marcinszymura/python_kurs pull request #4
Opened 2020-06-01 21:26 UTC by marcinszymura

2020-06-02 17:40 UTC, piotrgradzinski requested changes

2020-06-02 17:40 UTC, piotrgradzinski commented on homework/generator/generator.py
> +    yield sentence
Nie do końca o to chodzi i nie do końca działa tutaj idea geneatora, bo oddajesz całe zdanie, w senie wszystkie samogłoski i spacje (a tych akurat nie powinno być).
Wynik tego kodu:
```python
for char in vowels('ala ma kota a kot ma ale'):
    print(char)
```
powinien być taki:
```
a
a
a
o
a
a
o
a
a
e
```
Zwróć uwagę, że było 10 iteracji a w Twoim przypadku była tylko jedna.

2020-06-02 17:40 UTC, piotrgradzinski commented on homework/iterator/iterator.py
> +class Vowels:
Tutaj jest dokładnie ten sam problem co wcześniej.

2020-06-03 15:19 UTC, marcinszymura commented on homework/iterator/iterator.py
> +# Piotrze, traz zwraca None jak jest nie samogłoska, mogę zamieniac na " " ale dalej bedzie wyświetlany znak.
nie mam bladego pojęcia jak zwracać bez none

2020-06-03 15:22 UTC, marcinszymura commented on homework/generator/generator.py
> +    yield sentence
wydaje mi się ze poprawiłem

2020-06-03 20:54 UTC, piotrgradzinski requested changes

2020-06-03 20:54 UTC, piotrgradzinski commented on homework/iterator/iterator.py
> +# Piotrze, traz zwraca None jak jest nie samogłoska, mogę zamieniac na " " ale dalej bedzie wyświetlany znak.
Możesz spróbować coś takiego wypróbować:
```python
    def __next__(self) -> str:
        if self.counter >= len(self.sentence):
            raise StopIteration
        tmp = self.sentence[self.counter]
        while tmp not in self.vowels:
            self.counter += 1
            tmp = self.sentence[self.counter]
        else:
            self.counter += 1
        return tmp
```

2020-06-06 06:29 UTC, merged